fix AccessDeniedException: at java.base/sun.nio.fs.UnixException.translateToIOException
Error: Error while writing the APK Set archive to 'app.apks'.\n
java.io.UncheckedIOException: Error while writing the APK Set archive to 'app.apks'.\n\t
at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:176)\n\t
at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:235)\n\t
at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:110)\n\t
at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:524)\n\t
at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)\n\t
at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)\n
Caused by: java.nio.file.AccessDeniedException: /var/folders/8c/clfh0x3s6wg77ms0cdgcbt1w0000gn/T/ZipBuilder-8664783560618198172.zip.tmp -> app.apks\n\t
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)\n\t
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\t
at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:478)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)\n\t
at java.base/java.nio.file.Files.move(Files.java:1424)\n\tat com.android.tools.build.bundletool.io.ZipBuilder.writeTo(ZipBuilder.java:111)\n\t
at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.writeTo(ApkSetBuilderFactory.java:173)\n\t... 5 more\n